name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
 branches:
   include:
     - main

strategy:
  matrix:
    'Compile Against W1 - Current Version':
      artifactCountry: 'w1'
      artifactVersion: 'Current'
    'Compile Against W1 - Next Minor':
      artifactCountry: 'w1'
      artifactVersion: 'NextMinor'
    'Compile Against W1 - Next Major':
      artifactCountry: 'w1'
      artifactVersion: 'NextMajor'
    'Compile Against United States - Current Version':
      artifactCountry: 'us'
      artifactVersion: 'Current'
    'Compile Against United States - Next Minor':
      artifactCountry: 'us'
      artifactVersion: 'NextMinor'
    'Compile Against United States - Next Major':
      artifactCountry: 'us'
      artifactVersion: 'NextMajor'
    'Compile Against Canada - Current Version':
      artifactCountry: 'ca'
      artifactVersion: 'Current'
    'Compile Against Canada - Next Minor':
      artifactCountry: 'ca'
      artifactVersion: 'NextMinor'
    'Compile Against Canada - Next Major':
      artifactCountry: 'ca'
      artifactVersion: 'NextMajor'      

pool: Helgesen Build

variables:
- group: Secrets

schedules:
- cron: '0 0 * * *'
  displayName: Daily Midnight ALOps Compile against Current, Next Minor, and Next Major
  branches:
    include:
    - main
  always: true

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

- task: ALOpsAppCompiler@2
  displayName: 'Compile App'
  inputs:  
    artifacttype: 'Sandbox'
    artifactcountry: '$(artifactCountry)'
    versionselect: '$(artifactVersion)'
    appversiontemplate: '?.?.*.0'
    alcodeanalyzer: UICop,CodeCop,PerTenantExtensionCop
    failonwarnings: true
    publishartifact: false
    sastoken: $(bc.sastoken)
