name: $(Build.BuildId)

trigger:
 branches:
   include:
     - main

strategy:
  matrix:
    'W1':
      artifactCountry: 'w1'
    'US':
      artifactCountry: 'us'

pool: Helgesen Build

variables:
- group: Secrets

schedules:
- cron: '5 0 * * *'
  displayName: Daily Current Next Minor and Major build
  branches:
    include:
    - main
  always: true

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

- task: ALOpsAppCompiler@2
  displayName: 'Current'
  inputs:  
    artifacttype: 'Sandbox'
    artifactcountry: $artifactCountry
    appversiontemplate: '?.?.*.0'
    alcodeanalyzer: UICop,CodeCop,PerTenantExtensionCop
    ruleset: 'https://navmgtstorage00000000.blob.core.windows.net/backup/app.ruleset.json?sp=r&st=2021-01-17T11:45:50Z&se=2022-02-01T19:45:50Z&spr=https&sv=2019-12-12&sr=b&sig=Y%2BibBuN2cTg3%2FIasH9rigqGBoUCCb9rsSXsrwaW8f%2Fc%3D'
    
- task: ALOpsAppCompiler@2
  displayName: 'Next Minor'
  inputs:  
    artifacttype: 'Sandbox'
    artifactcountry: $artifactCountry
    versionselect: NextMinor
    appversiontemplate: '?.?.*.0'
    alcodeanalyzer: UICop,CodeCop,PerTenantExtensionCop
    ruleset: 'https://navmgtstorage00000000.blob.core.windows.net/backup/app.ruleset.json?sp=r&st=2021-01-17T11:45:50Z&se=2022-02-01T19:45:50Z&spr=https&sv=2019-12-12&sr=b&sig=Y%2BibBuN2cTg3%2FIasH9rigqGBoUCCb9rsSXsrwaW8f%2Fc%3D'
    sastoken: $(bc.sastoken)

- task: ALOpsAppCompiler@2
  displayName: 'Next Major'
  inputs:
    artifacttype: 'Sandbox'
    artifactcountry: $artifactCountry
    versionselect: NextMajor
    appversiontemplate: '?.?.*.0'
    alcodeanalyzer: UICop,CodeCop,PerTenantExtensionCop
    ruleset: 'https://navmgtstorage00000000.blob.core.windows.net/backup/app.ruleset.json?sp=r&st=2021-01-17T11:45:50Z&se=2022-02-01T19:45:50Z&spr=https&sv=2019-12-12&sr=b&sig=Y%2BibBuN2cTg3%2FIasH9rigqGBoUCCb9rsSXsrwaW8f%2Fc%3D'
    sastoken: $(bc.sastoken)